// src/components/taskbarProgram.vue
<script lang="ts" setup>
import { SvgIcon } from "#components";
import { ProgramMetadata, useProgramManager } from "~/composables/programManagement";
import { computed } from "#imports";

const programManager = useProgramManager();

const props = defineProps<{
    program: ProgramMetadata;
}>();

const dynClasses = computed(() => [
    programManager.getProgramVisibility(props.program.programId).value === "closed"
        ? "shadow-default"
        : "shadow-inverse",
    props.program.taskbarSize === "normal" ? "max-w-[200px]" : "max-w-[100px]",
]);

async function onClick(): Promise<void> {
    if (programManager.getProgramVisibility(props.program.programId).value === "closed") {
        await programManager.setProgramVisibility(props.program.programId, "opened", true);
    } else {
        if (programManager.getStackPosition(props.program.programId).value === 0) {
            await programManager.setProgramVisibility(props.program.programId, "closed");
        } else {
            await programManager.raiseWindow(props.program.programId);
        }
    }
}
</script>

<template>
    <div
        class="flex items-center grow bg-grey-normal px-1 py-1.5 m-2 select-none"
        :class="dynClasses"
        @click.stop="onClick"
    >
        <svg-icon :path="props.program.icon" />
        <span>{{ program.title }}</span>
    </div>
</template>

<style scoped></style>

// src/src/components/TaskbarProgram.svelte
<script lang="ts">
	import SvgIcon from "./SvgIcon.svelte";
	import type { ProgramMetadata } from "../ProgramManagement";
	import { ProgramManager, programState, ProgramVisibility } from "../ProgramManagement";

	export let metadata: ProgramMetadata;

	const state = programState(metadata.programId);
	const programManager = new ProgramManager();

	let shadowCssClass;
	$: shadowCssClass = $state.visibility === ProgramVisibility.CLOSED ? "shadow" : "shadow-inverse";

	function onClickProgram(): void {
		if ($state.visibility === ProgramVisibility.CLOSED) {
			programManager.setProgramVisibility(metadata.programId, ProgramVisibility.OPENED);
		} else if (!$state.isOnTop) {
			programManager.raiseWindow(metadata.programId);
		} else {
			programManager.setProgramVisibility(metadata.programId, ProgramVisibility.CLOSED);
		}
	}
</script>

<div class="taskbar-program no-select {shadowCssClass}" role="button" on:click={onClickProgram}>
	<SvgIcon path={metadata.icon} />
	<span>{metadata.title}</span>
</div>

<style lang="scss">
	@use "../styles/utils";
	@use "../styles/colors";

	.taskbar-program {
		max-width: 164px;
		background-color: colors.get_color("grey");
		margin: 3px 5px;
		padding: 2px 4px;
		display: flex;
		align-items: center;
		flex-grow: 1;

		&:first-child {
			max-width: 96px;
		}

		& > :first-child {
			margin-right: 6px;
		}
	}
</style>
