// src/components/TaskBar.vue
<template>
  <div class="task-bar">
    <task-bar-button text="Home" icon="microsoft-windows-classic" disabled/>
    <slot/>
  </div>
</template>

<script lang="ts">
  import Vue from 'vue';
  import Component from 'vue-class-component';
  import 'vue-class-component/hooks';
  import TaskBarButton from '@/components/TaskBarButton.vue';
  import {Prop} from 'vue-property-decorator';
  import VueTypes from 'vue-types';

  @Component({
    components: {TaskBarButton},
  })
  export default class TaskBar extends Vue {
  }
</script>

<style scoped lang="scss">
  @use "src/styles/colors";

  .task-bar {
    background-color: colors.get_color("grey");
    padding: 3px 8px;
    display: flex;
    flex-flow: row;
    align-content: baseline;
    border-top: 2px solid colors.get_color("shadow-raised");
    height: 40px;

    & > * {
      margin-right: 8px;
    }

    & > *:not(:first-child) {
      min-width: 128px;
    }
  }
</style>

// src/src/components/Taskbar.svelte
<script lang="ts">
	import SystemTray from "./SystemTray.svelte";
</script>

<div class="shadow taskbar fill">
	<div>
		<slot />
	</div>
	<SystemTray>
		<slot name="SystemTray" />
	</SystemTray>
</div>

<style lang="scss">
	@use "../styles/utils";
	@use "../styles/colors";

	.taskbar {
		background-color: colors.get_color("grey");
		display: flex;
		z-index: 999;
		flex-basis: var(--taskbar-height);
		max-height: var(--taskbar-height);

		& > *:first-child {
			display: flex;
			flex-grow: 1;
			gap: 4px;
		}
	}
</style>
