// src/src/components/Pixelflut.svelte
<script lang="ts">
	import { beforeUpdate, createEventDispatcher, onDestroy } from "svelte";
	import { browser } from "$app/env";
	import { PixelflutClient } from "pixelflut-client";

	let canvas: HTMLCanvasElement;
	let pixelflutClient: PixelflutClient;
	const dispatch = createEventDispatcher();

	if (browser) {
		beforeUpdate(() => {
			if (canvas && !pixelflutClient) {
				pixelflutClient = new PixelflutClient("wss://finn-thorben.me/pixelflut.sock", canvas, false);
				pixelflutClient.connect().then(() => {
					dispatch("sizeReceived", { width: pixelflutClient.width, height: pixelflutClient.height });
				});
			}
		});

		onDestroy(() => {
			if (pixelflutClient && pixelflutClient.isConnected()) {
				pixelflutClient.disconnect();
			}
		});
	}
</script>

<canvas bind:this={canvas} width="800" height="600" />

// src/components/pixelflut.vue
<script lang="ts" setup>
import { onBeforeUnmount, onMounted, ref } from "#imports";
import { PixelflutClient } from "pixelflut-client";

const canvas = ref<HTMLCanvasElement>();
let pixelflutClient: PixelflutClient;

const emit = defineEmits<{
    (e: "sizeReceived", width: number, height: number): void;
    (e: "connected"): void;
    (e: "disconnected"): void;
}>();

if (!process.server) {
    onMounted(async () => {
        pixelflutClient = new PixelflutClient("wss://finn-thorben.me/pixelflut.sock", canvas.value!, false);
        await pixelflutClient.connect();
        emit("connected");
        emit("sizeReceived", pixelflutClient.width, pixelflutClient.height);
    });

    onBeforeUnmount(async () => {
        if (pixelflutClient && pixelflutClient.isConnected()) {
            pixelflutClient.disconnect();
            emit("disconnected");
        }
    });
}
</script>

<template>
    <canvas ref="canvas" width="800" height="600" />
</template>

<style scoped></style>
