// src/src/components/SystemTrayProgram.svelte
<script lang="ts">
	import SvgIcon from "./SvgIcon.svelte";
	import type { ProgramMetadata } from "../ProgramManagement";
	import { ProgramManager, programState, ProgramVisibility } from "../ProgramManagement";

	export let metadata: ProgramMetadata;

	const state = programState(metadata.programId);
	const programManager = new ProgramManager();

	function onClick(): void {
		if ($state.visibility === ProgramVisibility.CLOSED) {
			programManager.setProgramVisibility(metadata.programId, ProgramVisibility.OPENED);
		} else if (!$state.isOnTop) {
			programManager.raiseWindow(metadata.programId);
		}
	}
</script>

<div class="system-tray-program" on:click={onClick}>
	<SvgIcon path={metadata.icon} />
</div>

<style lang="scss">
	@use "../styles/utils";
	@use "../styles/colors";

	.system-tray-program {
		border: 2px colors.get_color("grey") solid;
	}
	.system-tray-program:active:not(.non-interactive) {
		@include utils.shadow($inverse: true);
		border-style: dotted;
	}
</style>

// src/components/systemTrayProgram.vue
<script lang="ts" setup>
import { ProgramMetadata, useProgramManager } from "~/composables/programManagement";
import { SvgIcon } from "#components";

const programManager = useProgramManager();

const props = defineProps<{
    metadata: ProgramMetadata;
}>();

async function onClick(): Promise<void> {
    if (programManager.getProgramVisibility(props.metadata.programId).value === "closed") {
        await programManager.setProgramVisibility(props.metadata.programId, "opened", true);
    } else {
        if (programManager.getStackPosition(props.metadata.programId).value === 0) {
            await programManager.setProgramVisibility(props.metadata.programId, "closed");
        } else {
            await programManager.raiseWindow(props.metadata.programId);
        }
    }
}
</script>

<template>
    <SvgIcon
        class="border-solid border-2 border-grey active:border-shadow-inverse p-0.5"
        :size="28"
        :path="props.metadata.icon"
        @click.stop="onClick"
    />
</template>

<style scoped></style>
