// src/src/components/Viewport.svelte
<script lang="ts">
	import Window from "./Window.svelte";
	import Explorer from "./Explorer.svelte";
	import { setContext } from "svelte";
	import { CTX_PROGRAM_METADATAS, ProgramMetadata } from "../ProgramManagement";
	import { cvMetadata } from "./windows/Cv.svelte";
	import CvContent from "./windows/Cv.svelte";
	import { contactMetadata } from "./windows/contact.svelte";
	import ContactContent from "./windows/contact.svelte";
	import Taskbar from "./Taskbar.svelte";
	import TaskbarProgram from "./TaskbarProgram.svelte";
	import { mdiMicrosoftWindowsClassic } from "@mdi/js";
	import SystemTrayProgram from "./SystemTrayProgram.svelte";
	import ImprintContent from "./windows/Imprint.svelte";
	import { imprintMetadata } from "./windows/Imprint.svelte";
	import RickRollContent from "./windows/RickRoll.svelte";
	import { rickRollMetadata } from "./windows/RickRoll.svelte";
	import CodingContent from "./windows/Coding.svelte";
	import { codingMetadata } from "./windows/Coding.svelte";

	const startMenuMetadata: ProgramMetadata = {
		programId: "start",
		title: "Start",
		icon: mdiMicrosoftWindowsClassic,
		canOpen: true,
		renderDefaults: {
			x: "",
			y: "",
			width: "",
			height: "",
		},
	};

	setContext(CTX_PROGRAM_METADATAS, [
		startMenuMetadata,
		cvMetadata,
		contactMetadata,
		imprintMetadata,
		rickRollMetadata,
		codingMetadata,
	]);
</script>

<div class="split-container fill non-mobile">
	<Explorer>
		<Window metadata={cvMetadata}>
			<CvContent />
		</Window>
		<Window metadata={contactMetadata}>
			<ContactContent />
		</Window>
		<Window metadata={imprintMetadata}>
			<ImprintContent />
		</Window>
		<Window metadata={rickRollMetadata}>
			<RickRollContent />
		</Window>
		<Window metadata={codingMetadata}>
			<CodingContent />
		</Window>
	</Explorer>
	<Taskbar>
		<svelte:fragment>
			<TaskbarProgram metadata={startMenuMetadata} />
			<TaskbarProgram metadata={cvMetadata} />
			<TaskbarProgram metadata={contactMetadata} />
			<TaskbarProgram metadata={codingMetadata} />
		</svelte:fragment>
		<svelte:fragment slot="SystemTray">
			<SystemTrayProgram metadata={rickRollMetadata} />
			<SystemTrayProgram metadata={imprintMetadata} />
		</svelte:fragment>
	</Taskbar>
</div>

<style lang="scss">
	@use "../styles/utils";

	.split-container {
		display: flex;
		flex-direction: column;
		--taskbar-height: 48px;
	}
</style>

// src/components/viewport.vue
<template>
  <div class="split-container">
    <explorer>
      <window :metadata="cvMetadata" x="56px" y="56px">
        <cv />
      </window>
    </explorer>
    <taskbar>
      <taskbar-program :metadata="startMetadata" />
      <taskbar-program :metadata="cvMetadata" />
      <taskbar-program :metadata="contactMetadata" />
      <taskbar-program :metadata="codingMetadata" />
      <taskbar-program :metadata="imprintMetadata" />
    </taskbar>
  </div>
</template>

<script lang="ts">
import { Vue, Component } from 'nuxt-property-decorator'
import { mdiMicrosoftWindowsClassic, mdiAccount, mdiEmail, mdiCodeBraces, mdiGavel } from '@mdi/js'
import Taskbar from '~/components/taskbar.vue'
import Explorer from '~/components/explorer.vue'
import Cv from '~/components/windows/cv.vue'
import { WindowMetadata } from '~/utils/windowMetadata'

@Component({
  components: { Explorer, Taskbar, Cv }
})
export default class Viewport extends Vue {
  startMetadata: WindowMetadata = {
    title: 'Start',
    programId: 'start',
    icon: mdiMicrosoftWindowsClassic
  }

  cvMetadata: WindowMetadata = {
    title: 'CV',
    programId: 'cv',
    icon: mdiAccount
  }

  contactMetadata: WindowMetadata = {
    title: 'Contact',
    programId: 'contact',
    icon: mdiEmail
  }

  codingMetadata: WindowMetadata = {
    title: 'Coding',
    programId: 'coding',
    icon: mdiCodeBraces
  }

  imprintMetadata: WindowMetadata = {
    title: 'Imprint',
    programId: 'imprint',
    icon: mdiGavel
  }
}
</script>

<style scoped lang="scss">
.split-container {
  display: flex;
  flex-direction: column;
  --taskbar-height: 40px;

  & > *:first-child {
    flex-basis: 90%;
    flex-grow: 99;
  }

  & > *:nth-child(2) {
    flex-basis: var(--taskbar-height);
    flex-grow: 0;
    flex-shrink: 0;
  }
}
</style>
