// src/src/components/Window.svelte
<script lang="ts">
	import SvgIcon from "./SvgIcon.svelte";
	import { mdiWindowClose, mdiWindowMaximize, mdiWindowMinimize, mdiWindowRestore } from "@mdi/js";
	import type { ProgramMetadata } from "../ProgramManagement";
	import { ProgramVisibility, ProgramManager } from "../ProgramManagement";
	import { programState } from "../ProgramManagement";
	import { derived } from "svelte/store";

	export let metadata: ProgramMetadata;

	const programManager = new ProgramManager();
	const state = programState(metadata.programId);
	let maximizeButtonIcon: string;
	$: maximizeButtonIcon =
		$state.visibility === ProgramVisibility.MAXIMIZED ? mdiWindowRestore : mdiWindowMaximize;

	const style = derived(state, (state) => {
		const zIndex = 999 - state.programIndex;

		if (state.visibility === ProgramVisibility.MAXIMIZED) {
			return `--x: 0px; --y: 0px; --z-index: ${zIndex}; --preferred-width: 999vw; --preferred-height: 999vh;`;
		} else {
			return `--x: ${state.placement.x}; --y: ${state.placement.y}; --z-index: ${zIndex}; --preferred-width: ${state.placement.width}; --preferred-height: ${state.placement.height};`;
		}
	});
</script>

{#if $state.visibility !== ProgramVisibility.CLOSED}
	<!-- Window wrapper -->
	<div
		on:mousedown={programManager.raiseWindow(metadata.programId)}
		class="window"
		class:on-top={$state.isOnTop}
		class:maximized={$state.visibility === ProgramVisibility.MAXIMIZED}
		style={$style}
	>
		<!-- Titlebar -->
		<div class="titlebar no-select">
			<div class="titlebar-title">{metadata.title}</div>
			<div class="button-container">
				<div
					class="button"
					on:click|stopPropagation={programManager.toggleProgramMinimization(metadata.programId)}
				>
					<SvgIcon size="22" path={mdiWindowMinimize} />
				</div>
				<div
					class="button"
					on:click|stopPropagation={programManager.toggleProgramMaximization(metadata.programId)}
				>
					<SvgIcon size="22" path={maximizeButtonIcon} />
				</div>
				<div
					class="button"
					on:click|stopPropagation={programManager.setProgramVisibility(
						metadata.programId,
						ProgramVisibility.CLOSED,
					)}
				>
					<SvgIcon size="22" path={mdiWindowClose} />
				</div>
			</div>
		</div>

		<!-- Content -->
		<div class="content-container" class:hidden={$state.visibility === ProgramVisibility.MINIMIZED}>
			<slot>Add content to this window in its slot</slot>
		</div>
	</div>
{/if}

<style lang="scss">
	@use "../styles/utils";
	@use "../styles/colors";

	.window {
		position: absolute;
		left: var(--x);
		top: var(--y);
		z-index: var(--z-index);
		@include utils.shadow();

		--titlebar-height: 32px;
		// the complete explorer screen minus x position
		--window-max-width: calc(100vw - var(--x));
		// the complete explorer screen minus y position minus taskbar height
		--window-max-height: calc(100vh - var(--y) - var(--taskbar-height));
		max-width: var(--window-max-width);
		max-height: var(--window-max-height);

		& .titlebar {
			display: flex;
			justify-content: space-between;
			align-items: center;
			background-color: colors.get_color("grey-dark");
			height: var(--titlebar-height);

			& .titlebar-title {
				margin: 4px;
				font-size: large;
				font-weight: lighter;
			}

			& .button-container {
				margin: 0 4px;
				display: flex;
				gap: 3px;

				& .button {
					background-color: colors.get_color("grey-light");
					@include utils.shadow();
				}

				& .button:active {
					@include utils.shadow($inverse: true);
				}
			}
		}

		& .content-container {
			@include utils.shadow($inverse: true);
			background-color: colors.get_color("white");
			padding: 4px;
			overflow: scroll;

			// the same as the containing window minus border (2*2px)
			max-width: min(calc(var(--window-max-width) - 4px), var(--preferred-width));
			// the same as the containing window minus titlebar height minus border (2*2px)
			max-height: min(calc(var(--window-max-height) - var(--titlebar-height) - 4px), var(--preferred-height));
		}
	}

	.window.on-top .titlebar {
		background-image: colors.get_color("titlebar-gradient");

		& .titlebar-title {
			color: colors.get_color("white");
		}
	}

	.window.maximized {
		width: 100%;
		height: 100%;

		& .content-container {
			width: 100%;
			height: 100%;
		}
	}
</style>

// src/components/Window.vue
<template>
  <div v-if="isOpen" class="window" :class="classes" @click="onWindowClick" :style="{ 'z-index': stackIndex }">
    <div class="titlebar no-select">
      <h1 class="titlebar-title">{{ title }}</h1>
      <div class="titlebar-button-container">
        <span class="titlebar-button mdi mdi-window-minimize" @click.stop="onClose"/>
        <span class="titlebar-button mdi mdi-window-maximize" @click.stop="onMaximize"/>
        <span class="titlebar-button mdi mdi-window-close" @click.stop="onClose"/>
      </div>
    </div>
    <div class="body">
      <slot/>
    </div>
  </div>
</template>

<script lang="ts">
  import Vue from 'vue';
  import Component from 'vue-class-component';
  import 'vue-class-component/hooks';
  import {Prop} from 'vue-property-decorator';
  import VueTypes from 'vue-types';

  @Component({})
  export default class Window extends Vue {
    @Prop(VueTypes.string.isRequired) readonly title!: string;

    @Prop(VueTypes.integer.def(0)) readonly stackNumber!: number;

    get isOpen(): boolean {
      return this.$isAppOpen(this.title.toLowerCase())
    }

    get classes(): string[] {
      return [
        this.$isAppMaximized(this.title.toLowerCase()) ? 'maximized' : '',
        this.$isAppOnTop(this.title.toLowerCase()) ? 'on-top' : ''
      ]
    }

    get stackIndex(): number {
      return this.$getAppStackIndex(this.title.toLowerCase())
    }

    onMaximize(): void {
      this.$toggleAppMaximized(this.title.toLowerCase());
    }

    onClose(): void {
      this.$toggleApp(this.title.toLowerCase())
    }

    onWindowClick(): void {
      this.$raiseApp(this.title.toLowerCase())
    }
  }
</script>

<style scoped lang="scss">
  @use "src/styles/colors";
  @use "src/styles/shadows";

  .window {
    position: absolute;
    @include shadows.shadow($thickness: 3px);

    &:not(.maximized) .body {
      max-width: 75vw;
      max-height: 80vh;
    }
    &.maximized {
      top: 0 !important;
      left: 0 !important;
      width: 100vw !important;
      height: calc(100vh - 40px) !important;

      & .body {
        width: 100%;
        height: 100%;
      }
    }

    &.on-top .titlebar {
      background: colors.get_color("topbar-gradient");
      color: colors.get_color("grey");
    }
    &:not(.on-top) .titlebar {
      background-color: colors.get-color("grey-dark");
    }

    .titlebar {
      display: flex;
      justify-content: space-between;
      align-content: baseline;

      .titlebar-title {
        margin: 3px 0 2px 4px;
        font-size: large;
        font-weight: lighter;
      }

      .titlebar-button-container {
        display: flex;
        align-items: center;

        .titlebar-button {
          margin: 0 2px;
          padding-left: 2px;
          width: 18px;
          height: 18px;
          background-color: colors.get_color("grey");
          color: colors.get_color("black");
          @include shadows.shadow();

          &:active {
            @include shadows.shadow($inverse: true);
          }
        }
      }
    }

    .body {
      background-color: colors.get_color("white");
      @include shadows.shadow($inverse: true);
      padding: 6px 4px 4px;
      overflow: scroll;
    }
  }
</style>
